#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    

    printf "\n\t%-9s  %-40s"  "1.1"       "SiC-PIN"
    printf "\n\t%-9s  %-40s\n"  "1.2"       "SiC-3D"

    printf "\n\t%-9s  %-40s\n"  "2.1"       "SiC-LGAD"

    printf "\n\t%-9s  %-40s"  "3.1"       "top-TCT"
    printf "\n\t%-9s  %-40s\n"  "3.2"       "edge-TCT"
    printf "\n"
}

usage_1_1() { 
	printf "\n\t%-5s  %-40s\n"  "1.1.0"    "Loading TRACK into Singularity..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.1"    "NJU-SiC-PIN basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "1.1.3"    "get time resolution for NJU-SiC-PIN" 
    printf "\n"
}
usage_1_2() { 
	printf "\n\t%-5s  %-40s\n"  "1.2.0"    "Loading TRACK into Singularity..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.1"    "3D-SiC basic information for RASER simulation ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.2.T"  "pre-run 3D-SiC batch model with total number, split with step number ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.2"    "run 3D-SiC batch model with total number, split with step number ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.3"    "get time resolution 3D-SiC multi points voltage [-50,-500] ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.4"    "get time resolution vs draw voltage ..." 
    printf "\n"
}

usage_2_1() { 
	printf "\n\t%-5s  %-40s\n"  "2.1.0"    "Loading TRACK into Singularity..." 
    printf "\n\t%-5s  %-40s\n"  "2.1.1"    "SiC-LGAD basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "2.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "2.1.3"    "get time resolution for SiC-LGAD, multi points doping [1e5,7e5]"
    printf "\n\t%-5s  %-40s\n"  "2.1.4"    "get time resolution vs doping ..." 
    printf "\n"
}

usage_3_1() { 
	printf "\n\t%-5s  %-40s\n"  "3.1.0"    "Loading TRACK into Singularity..." 
    printf "\n\t%-5s  %-40s\n"  "3.1.1"    "SiC-PIN top-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.1.2"    "SiC-LGAD top-TCT basic information ..."
    printf "\n"
}

usage_3_2() { 
	printf "\n\t%-5s  %-40s\n"  "3.2.0"    "Loading TRACK into Singularity..." 
    printf "\n\t%-5s  %-40s\n"  "3.2.1"    "SiC-PIN edge-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.2.2"    "SiC-LGAD edge-TCT basic information ..."
    printf "\n"
}

if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	input_para=$* 
fi

track(){
    singularity shell -B /cefs,/afs,/cvmfs,/scratchfs /cvmfs/container.ihep.ac.cn/userimages/track-1.2.sif 
}

geant4(){
    export GEANT4_INSTALL=/cvmfs/common.ihep.ac.cn/software/geant4/10.7.p02/install
    source $GEANT4_INSTALL/bin/geant4.sh
    export PYTHONPATH=$PYTHONPATH:$GEANT4_INSTALL/lib64/python3.6/site-packages  
}

hepjob(){
export HepcMyImage=track-1.2.sif
export PATH=$PATH:/afs/.ihep.ac.cn/soft/common/sysgroup/hepjob-4.0-dev/bin/
}

sub_1_1(){
case $option in 
    1.1.0) echo "Loading TRACK into Singularity..."
        track 
        ;; 
    1.1.1) echo "SiC-PIN basic information for RASER simulation ..."
        geant4 
        ./python/gsignal.py det_name=NJU-PIN parfile=setting.json
        ;;

	1.1.2) echo "batch model with total number, split with step number"
		hepjob
		./python/run_batchjob.py det_name=NJU-PIN step=100000 total=2000000 \
							 instance=0 output=out/planar3Dscan/20220323_3D/ batch=True para_name="NO" para_number=1 
        ;;

    1.1.3) echo "get time resolution for SiC-PIN"
        ./python/add_noise_raser.py out/planar3Dscan/20220323_3D/_d=10.0_v=-500.0_tmp=300.0_thick=100.0 1
        ;;
        esac
}

sub_1_2(){
case $option in 
    1.2.0) echo "Loading TRACK into Singularity..."
        track 
        ;; 
    1.2.1) echo "3D-SiC basic information for RASER simulation ..."
        geant4 
        ./python/gsignal.py det_name=plugin3D parfile=setting.json
        ;;
    1.2.2.T) echo "pre-run 3D-SiC batch model with total number, split with step number ..."
        hepjob
		./python/run_batchjob.py det_name=plugin3D step=200 total=400  \
							 instance=0 output=out/plugin3Dthick_20220608/ batch=True para_name=scan_voltage para_number=10
		;; 
    1.2.2) echo "run 3D-SiC batch model with total number, split with step number ..."
        hepjob
		./python/run_batchjob.py det_name=plugin3D step=20000 total=40000  \
							 instance=0 output=out/plugin3Dthick_20220608/ batch=True para_name=scan_voltage para_number=10 
        ;;
	1.2.3) echo "get time resolution 3D-SiC multi points voltage [-50,-500]"
        ./python/time_scan.py  out/plugin3Dthick_20220608 scan
			;;
	1.2.4) echo "get time resolution vs draw voltage"
		./python/time_scan.py  out/plugin3Dthick_20220608/time_resolution_scan.csv draw_voltage 0
			;;
        esac
}

sub_2_1(){
case $option in 
    2.1.0) echo "Loading TRACK into Singularity..."
        track 
        ;; 
    2.1.1) echo "SiC-LGAD basic information for RASER simulation ..."
        geant4 
        ./python/gsignal.py det_name=SICAR-1 parfile=setting.json
        ;;

	2.1.2) echo "batch model with total number, split with step number"
		hepjob
		./python/run_batchjob.py det_name=SICAR-1  step=200000 total=400000 \
							 instance=0 output=out/lgad3Dscan/ batch=True para_name=scan_doping para_number=8
        ;;

    2.1.3) echo "get time resolution for SiC-LGAD, multi points doping [1e5,7e5]"
        hepjob
        ./python/time_scan.py  out/lgad3Dscan scan
        ;;

    2.1.4) echo "get time resolution and gain efficiency vs avalanche doping"
		./python/time_scan.py  out/lgad3Dscan/time_resolution_scan.csv draw_doping 0
        ./python/time_scan.py  out/lgad3Dscan/gain_efficiency_scan.csv gain_doping 0
		;;
    esac
}

sub_3_1(){
case $option in 
    3.1.0) echo "Loading TRACK into Singularity..."
        track 
        ;; 
    3.1.1) echo "SiC-PIN top-TCT basic information ..."
        geant4 
        ./python/TCTtest.py det_name=NJU-PIN parfile=setting.json laser_model=top_TCT laser_parfile=laser_setting.json
        ;;
    3.1.2) echo "SiC-LGAD top-TCT basic information ..."
        geant4 
        ./python/TCTtest.py det_name=SICAR-1 parfile=setting.json laser_model=top_TCT laser_parfile=laser_setting.json
        ;;
        esac
}

sub_3_2(){
case $option in 
    3.2.0) echo "Loading TRACK into Singularity..."
        track 
        ;; 
    3.2.1) echo "SiC-PIN edge-TCT basic information ..."
        geant4 
        ./python/TCTtest.py det_name=NJU-PIN parfile=setting.json laser_model=edge_TCT_Si laser_parfile=laser_setting.json
        ;;
        esac
}

case $option in 
    1.1) echo "RASER simulate NJU-SiC-PIN"
        usage_1_1
        echo "Please enter your option: " 
        read option 
        sub_1_1 option 
        ;;
    1.1.*) echo "RASER simulate NJU-SiC-PIN"
        sub_1_1 option
        ;;

    1.2) echo "RASER simulate 3D-SiC"
        usage_1_2
        echo "Please enter your option: " 
        read option 
        sub_1_2 option 
        ;;
    1.2.*) echo "RASER simulate 3D-SiC"
        sub_1_2 option
        ;;

    2.1) echo "RASER simulate SiC-LGAD"
        usage_2_1
        echo "Please enter your option: " 
        read option 
        sub_2_1 option 
        ;;
    2.1.*) echo "RASER simulate SiC-LGAD"
        sub_2_1 option
        ;;

    3.1) echo "RASER simulate top-TCT"
        usage_3_1
        echo "Please enter your option: " 
        read option 
        sub_3_1 option 
        ;;
    3.1.*) echo "RASER simulate top-TCT"
        sub_3_1 option
        ;;



    3.2) echo "RASER simulate edge-TCT"
        usage_3_2
        echo "Please enter your option: " 
        read option 
        sub_3_2 option 
        ;;
    3.2.*) echo "RASER simulate edge-TCT"
        sub_3_2 option
        ;;


		esac
