#!/usr/bin/env bash        
# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    

    printf "\n\t%-9s  %-40s"    "1.1"       "SiC-PIN"
    printf "\n\t%-9s  %-40s\n"  "1.2"       "SiC-3D"
    printf "\n\t%-9s  %-40s\n"  "1.3"       "DEVSIM"

    printf "\n\t%-9s  %-40s"    "2.1"       "SiC-LGAD"
    printf "\n\t%-9s  %-40s\n"  "2.2"       "Si-LGAD"

    printf "\n\t%-9s  %-40s"    "3.1"       "top-TCT"
    printf "\n\t%-9s  %-40s"    "3.2"       "edge-TCT-Si"
    printf "\n\t%-9s  %-40s"    "3.3"       "edge-TCT-SiC"

    printf "\n"
}

usage_1_1() { 
    printf "\n\t%-5s  %-40s\n"  "1.1.1"    "NJU-SiC-PIN basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "1.1.3"    "get time resolution for NJU-SiC-PIN" 
    printf "\n\t%-5s  %-40s\n"  "1.1.4"    "HPK-Si-PIN basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.5"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "1.1.6"    "get time resolution for HPK-Si-PIN" 
    printf "\n\t%-5s  %-40s\n"  "1.1.7"    "NJU-SiC-PIN beam monitor" 
    printf "\n"
}
usage_1_2() { 
	printf "\n\t%-5s  %-40s\n"  "1.2.1"    "3D-SiC basic information for RASER simulation ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.2"    "3D-SiC batch model with total number, split with step number ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.3"    "get time resolution 3D-SiC multi points voltage [-50,-500] ..." 
	printf "\n\t%-5s  %-40s\n"  "1.2.4"    "get time resolution vs draw voltage ..." 
    printf "\n"
}

usage_1_3() { 
    printf "\n\t%-5s  %-40s\n"  "1.3.1"    "Initial DataBase of DEVSIM" 
    printf "\n\t%-5s  %-40s\n"  "1.3.2"    "Build 1D NJU-PIN structure"
    printf "\n\t%-5s  %-40s\n"  "1.3.3"    "Simulate 1D NJU-PIN I-V"
    printf "\n\t%-5s  %-40s\n"  "1.3.4"    "Simulate 1D NJU-PIN C-V"
    printf "\n\t%-5s  %-40s\n"  "1.3.5"    "Build 1D SICAR LGAD structure"
    printf "\n\t%-5s  %-40s\n"  "1.3.6"    "Simulate 1D SICAR LGAD I-V"
    printf "\n\t%-5s  %-40s\n"  "1.3.7"    "Simulate 1D SICAR LGAD C-V"
}

usage_2_1() { 
    printf "\n\t%-5s  %-40s\n"  "2.1.1"    "SiC-LGAD basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "2.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "2.1.3"    "get time resolution for SiC-LGAD, multi points doping [1e5,7e5]"
    printf "\n\t%-5s  %-40s\n"  "2.1.4"    "get time resolution vs doping ..." 
    printf "\n"
}

usage_2_2() { 
    printf "\n\t%-5s  %-40s\n"  "2.2.1"    "Si-LGAD basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "2.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "2.1.3"    "get time resolution for Si-LGAD, multi points voltage [200,250]"
    printf "\n\t%-5s  %-40s\n"  "2.1.4"    "get time resolution vs voltage ..." 
    printf "\n"
}

usage_3_1() { 
    printf "\n\t%-5s  %-40s\n"  "3.1.1"    "SiC-PIN top-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.1.2"    "SiC-LGAD top-TCT basic information ..."
    printf "\n"
}

usage_3_2() {
    printf "\n\t%-5s  %-40s\n"  "3.2.1"    "Si-PIN edge-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.2.2"    "Si-LGAD edge-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.2.3"    "get volt-time for Si-PIN, multi points z [0,50]"
    printf "\n\t%-5s  %-40s\n"  "3.2.4"    "get volt-time for Si-LGAD, multi points z [0,50]"
    printf "\n\t%-5s  %-40s\n"  "3.2.4"    "analyse eTCT rootfiles "
    printf "\n\n"
}

usage_3_3() {
    printf "\n\t%-5s  %-40s\n"  "3.3.1"    "SiC-PIN edge-TCT basic information ..."
    printf "\n\t%-5s  %-40s\n"  "3.3.2"    "get volt-time for Si-PIN, multi points z [0,100]"
    printf "\n\n"
}

if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	input_para=$* 
fi


imagename=raser-1.2.sif
export PATH=/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:$PATH

raser(){
    apptainer exec --env-file cfg/env -B /cefs,/afs,/besfs5,/cvmfs,/scratchfs /cvmfs/container.ihep.ac.cn/userimages/$imagename $1 
}

sub_1_1(){
case $option in 
    1.1.1) echo "SiC-PIN basic information for RASER simulation ..." 
        raser "./python/gsignal.py det_name=NJU-PIN parfile=paras/setting.json" 
        ;;

	1.1.2) echo "batch model with total number, split with step number"
		step=100000
		for ((i=0;i<20;i++))
        do
            ./python/run_batchjob.py pin3D/NJU-PIN \
                "gsignal.py det_name=NJU-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/NJU-PIN/"
        done
        ;;

    1.1.3) echo "get time resolution for SiC-PIN"
        ./python/add_noise_raser.py output/pin3D/NJU-PIN/_d=10.0_v=-500.0_tmp=300.0_thick=100.0_radius=None 1
        ;;

    1.1.2S) echo "run 3D-SiC batch model with total number, split with step number ..."
        step=10000
		for ((i=0;i<2;i++))
        do
            for ((j=0;j<10;j++))
            do
                ./python/run_batchjob.py pin3D/NJU-PIN \
                "gsignal.py det_name=NJU-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/NJU-PIN/ parameter_alter=True voltage=$[-500-j*20]"
            done
        done
        ;;

	1.1.3S) echo "get time resolution 3D-SiC multi points voltage [-50,-500]"
        ./python/time_scan.py  output/pin3D/NJU-PIN/ scan
		;;

    1.1.4S) echo "get time resolution vs draw voltage"
		./python/time_scan.py  output/pin3D/NJU-PIN/time_resolution_scan.csv draw_voltage 0
		;;

    1.1.1A) echo "Si-PIN basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=HPK-Si-PIN parfile=paras/setting.json"
        ;;

    1.1.2A) echo "batch model with total number, split with step number"
		step=10000
		for ((i=0;i<20;i++))
        do
            ./python/run_batchjob.py pin3D/HPK-Si-PIN \
                "gsignal.py det_name=HPK-Si-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/HPK-Si-PIN/"
        done
        ;;

    1.1.3A) echo "get time resolution for Si-PIN"
        ./python/add_noise_raser.py output/pin3D/HPK-Si-PIN/_d=-1.0_v=200.0_tmp=300.0_thick=50.0_radius=None 1
        ;;

    1.1.7) echo "SiC-PIN beam monitor" 
        raser "./python/gsignal.py det_name=NJU-PIN-Beam-monitor parfile=paras/setting.json beammonitor" 
        ;;
        esac
}

sub_1_2(){
case $option in 
    1.2.1) echo "3D-SiC basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=plugin3D parfile=paras/setting.json"
		;;

    1.2.2) echo "run 3D-SiC batch model with total number, split with step number ..."
        step=10000
		for ((i=0;i<2;i++))
        do
            for ((j=0;j<10;j++))
            do
                ./python/run_batchjob.py plugin3D/plugin3D \
                "gsignal.py det_name=plugin3D parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/plugin3D/plugin3D/ parameter_alter=True voltage=$[-500+j*50]"
                # doping=$[10+j*10]
                # temp=$[300+j*30]
                # lz=$[150.0+j*30]
                # e_gap=$[140.0+j*20]
            done
        done
        ;;

	1.2.3) echo "get time resolution 3D-SiC multi points voltage [-50,-500]"
        ./python/time_scan.py  output/plugin3D/plugin3D/ scan
		;;

	1.2.4) echo "get time resolution vs draw voltage"
		./python/time_scan.py  output/plugin3D/plugin3D/time_resolution_scan.csv draw_voltage 0
		;;
        esac
}

sub_1_3(){
case $option in 
    1.3.1) echo "Initial DataBase of DEVSIM ..."
        raser "./python/gen_devsim_db.py"
        ;;

    1.3.2) echo "Build 1D NJU-PIN structure ..."
        raser "./python/nju_pin_5mm_5mm_mesh.py"
        ;;

    1.3.3) echo "Simulate 1D NJU-PIN I-V ..."
        ./python/run_batchjob.py devsim "solve_iv_pin.py"
        ;;

    1.3.4) echo "Simulate 1D NJU-PIN C-V ..."
        ./python/run_batchjob.py devsim "solve_cv_pin.py"
        ;;

    1.3.5) echo "Build 1D SICAR1 LGAD structure ..."
        raser "./python/sicar1_lgad_mesh.py"
        ;;

    1.3.6) echo "Simulate 1D SICAR1 LGAD I-V ..."
        ./python/run_batchjob.py devsim "solve_iv_lgad.py"
        ;;

    1.3.7) echo "Simulate 1D SICAR1 LGAD C-V ..."
        ./python/run_batchjob.py devsim "solve_cv_lgad.py"
        ;;
        esac
}

sub_2_1(){
case $option in 
    2.1.1) echo "SiC-LGAD basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=SICAR-1 parfile=paras/setting.json" 
        ;;

	2.1.2) echo "batch model with total number, split with step number"
        step=50000
		for ((i=0;i<4;i++))
        do
            for ((j=0;j<10;j++))
            do
                ./python/run_batchjob.py lgad3D/SICAR-1 \
                "gsignal.py det_name=SICAR-1 parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/lgad3D/SICAR-1/ parameter_alter=True voltage=$[-400-j*10]"
            done
        done
        ;;

    2.1.3) echo "get time resolution for SiC-LGAD, multi points voltage [200,250]"
        ./python/time_scan.py  output/lgad3D/SICAR-1 scan
        ;;

    2.1.4) echo "get time resolution and gain efficiency vs avalanche doping"
		./python/time_scan.py  output/lgad3D/SICAR-1/time_resolution_scan.csv draw_voltage 0
        ./python/time_scan.py  output/lgad3D/SICAR-1/gain_efficiency_scan.csv gain_voltage 0
		;;
    esac
}


sub_2_2(){
case $option in 
    2.2.1) echo "Si-LGAD basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=HPK-Si-LGAD parfile=paras/setting.json"
        ;;

    2.2.2) echo "batch model with total number, split with step number"
        step=50000
		for ((i=1;i<=4;i++))
        do
            for ((j=1;j<=5;j++))
            do
                ./python/run_batchjob.py lgad3D/HPK-Si-LGAD \
                "gsignal.py det_name=HPK-Si-LGAD parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/lgad3D/HPK-Si-LGAD/ parameter_alter=True voltage=$[200+j*10]"
            done
        done
        ;;

    2.2.3) echo "get time resolution for Si-LGAD, multi points voltage [200,250]"
        ./python/time_scan.py  output/lgad3D/HPK-Si-LGAD scan
        ;;

    2.2.4) echo "get time resolution and gain efficiency vs avalanche doping"
		./python/time_scan.py  output/lgad3D/HPK-Si-LGAD/time_resolution_scan.csv draw_voltage 0
        ./python/time_scan.py  output/lgad3D/HPK-Si-LGAD/gain_efficiency_scan.csv gain_voltage 0
		;;
    esac
}


sub_3_1(){
case $option in 
    3.1.1) echo "SiC-PIN top-TCT basic information ..."
        raser "./python/TCTtest.py det_name=NJU-PIN parfile=paras/setting.json laser_model=top_TCT laser_parfile=paras/laser_setting.json"
        ;;

    3.1.2) echo "SiC-LGAD top-TCT basic information ..."
        raser "./python/TCTtest.py det_name=SICAR-1 parfile=paras/setting.json laser_model=top_TCT laser_parfile=paras/laser_setting.json" 
        ;;
        esac
}


sub_3_2(){
case $option in
    3.2.1) echo "Si-PIN edge-TCT basic information ..."
        raser "./python/TCTtest.py det_name=HPK-Si-PIN parfile=paras/setting.json laser_model=edge_TCT_Si laser_parfile=paras/laser_setting.json"        
        ;;

    3.2.2) echo "Si-LGAD edge-TCT basic information ..."
        raser "./python/TCTtest.py det_name=HPK-Si-LGAD parfile=paras/setting.json laser_model=edge_TCT_Si laser_parfile=paras/laser_setting.json"       
        ;;

    3.2.3) echo "get volt-time for Si-PIN edge-TCT, multi points z [0,50]"
        step=1
        k=0.02

            for ((j=0;j<51;j++))
            do
                z=$(echo $k $j|awk '{printf "%0.2f\n", $1*$2}')
                ./python/run_batchjob.py pintct/HPK-Si-PIN \
                "TCTtest.py det_name=HPK-Si-PIN parfile=paras/setting.json laser_model=edge_TCT_Si laser_parfile=paras/laser_setting.json scan=True total_e=$step instan=1 output=output/pintct/HPK-Si-PIN/ parameter_alter=True fz_rel=$z"
            done 
            ;;  
 
    3.2.4) echo "get volt-time for Si-PIN edge-TCT, multi points Vbias [0,200]"
        step=1
        k=0.02
            for ((j=0;j<51;j++))
            do
                z=$(echo $k $j|awk '{printf "%0.2f\n", $1*$2}')
                ./python/run_batchjob.py lgadtct/HPK-Si-LGAD \
                "TCTtest.py det_name=HPK-Si-LGAD parfile=paras/setting.json laser_model=edge_TCT_Si laser_parfile=paras/laser_setting.json scan=True total_e=$step instan=1 output=output/lgadtct/HPK-Si-LGAD/ parameter_alter=True fz_rel=$z"
            done            
            ;;
    3.2.5) echo "analyse eTCT rootfiles"
            ./python/tct_analysis.py output/pintct/HPK-Si-PIN/
            ./python/tct_analysis.py output/lgadtct/HPK-Si-LGAD/
        esac
}

sub_3_3(){
case $option in
    3.3.1) echo "SiC-PIN edge-TCT basic information ..."
           raser "./python/TCTtest.py det_name=NJU-SiC-PIN parfile=paras/setting.json laser_model=edge_TCT_SiC laser_parfile=paras/laser_setting.json"        
        ;;
    3.3.2) echo "get volt-time for SiC-PIN edge-TCT, multi points z [0,50]"
                step=1
                k=0.01
            for ((j=0;j<101;j++))
            do
                z=$(echo $k $j|awk '{printf "%0.2f\n", $1*$2}')
                ./python/run_batchjob.py pintct/NJU-SiC-PIN \
                "TCTtest.py det_name=NJU-SiC-PIN parfile=paras/setting.json laser_model=edge_TCT_SiC laser_parfile=paras/laser_setting.json scan=True total_e=$step instan=1 output=output/pintct/NJU-SiC-PIN/ parameter_alter=True fz_rel=$z"
            done
        ;;

        esac
}

case $option in 
    1.1) echo "RASER simulate NJU-SiC-PIN"
        usage_1_1
        echo "Please enter your option: " 
        read option 
        sub_1_1 option 
        ;;
    1.1.*) echo "RASER simulate NJU-SiC-PIN"
        sub_1_1 option
        ;;

    1.2) echo "RASER simulate 3D-SiC"
        usage_1_2
        echo "Please enter your option: " 
        read option 
        sub_1_2 option 
        ;;
    1.2.*) echo "RASER simulate 3D-SiC"
        sub_1_2 option
        ;;

    1.3) echo "DEVSIM"
        usage_1_3
        echo "Please enter your option: " 
        read option 
        sub_1_3 option 
        ;;
    1.3.*) echo "DEVSIM"
        sub_1_3 option
        ;;

    2.1) echo "RASER simulate SiC-LGAD"
        usage_2_1
        echo "Please enter your option: " 
        read option 
        sub_2_1 option 
        ;;
    2.1.*) echo "RASER simulate SiC-LGAD"
        sub_2_1 option
        ;;

    2.2) echo "RASER simulate Si-LGAD"
        usage_2_2
        echo "Please enter your option: " 
        read option 
        sub_2_2 option 
        ;;
    2.2.*) echo "RASER simulate Si-LGAD"
        sub_2_2 option
        ;;

    3.1) echo "RASER simulate top-TCT"
        usage_3_1
        echo "Please enter your option: " 
        read option 
        sub_3_1 option 
        ;;
    3.1.*) echo "RASER simulate top-TCT"
        sub_3_1 option
        ;;

    3.2) echo "RASER simulate edge-TCT"
        usage_3_2
        echo "Please enter your option: "
        read option
        sub_3_2 option
        ;;
    3.2.*) echo "edge-TCT measurement"
        sub_3_2 option
        ;;

    3.3) echo "RASER simulate edge-TCT"
        usage_3_3
        echo "Please enter your option: "
        read option
        sub_3_3 option
        ;;
    3.3.*) echo  "RASER simulate edge-TCT"
        sub_3_3 option
        ;;

		esac
