#!/usr/bin/env bash        
# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    

    printf "\n\t%-9s  %-40s"    "1.1"       "SiC-PIN"
    printf "\n\t%-9s  %-40s\n"  "1.2"       "SiC-3D"
    printf "\n\t%-9s  %-40s\n"  "1.3"       "DEVSIM"

    printf "\n\t%-9s  %-40s"    "2.1"       "SiC-LGAD"
    printf "\n\t%-9s  %-40s\n"  "2.2"       "Si-LGAD"

    printf "\n\t%-9s  %-40s"    "3.1"       "top-TCT"
    printf "\n\t%-9s  %-40s"    "3.2"       "edge-TCT-Si"
    printf "\n\t%-9s  %-40s"    "3.3"       "edge-TCT-SiC"

    printf "\n"
}

usage_1_1() { 
    printf "\n\t%-5s  %-40s\n"  "1.1.1"    "NJU-SiC-PIN basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.2"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "1.1.3"    "get time resolution for NJU-SiC-PIN" 
    printf "\n\t%-5s  %-40s\n"  "1.1.4"    "HPK-Si-PIN basic information for RASER simulation ..." 
    printf "\n\t%-5s  %-40s\n"  "1.1.5"    "batch model with total number, split with step number" 
    printf "\n\t%-5s  %-40s\n"  "1.1.6"    "get time resolution for HPK-Si-PIN" 
    printf "\n\t%-5s  %-40s\n"  "1.1.7"    "NJU-SiC-PIN beam monitor" 
    printf "\n"
}


if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	input_para=$* 
fi


imagename=raser-1.2.sif
export PATH=/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:$PATH

raser(){
    apptainer exec --env-file cfg/env -B /cefs,/afs,/besfs5,/cvmfs,/scratchfs /cvmfs/container.ihep.ac.cn/userimages/$imagename $1 
}

sub_1_1(){
case $option in 
    1.1.1) echo "SiC-PIN basic information for RASER simulation ..." 
        raser "./python/gsignal.py det_name=NJU-PIN parfile=paras/setting.json scan=True" 
        ;;

	1.1.2) echo "batch model with total number, split with step number"
		step=100000
		for ((i=0;i<20;i++))
        do
            ./python/run_batchjob.py pin3D/NJU-PIN \
                "gsignal.py det_name=NJU-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/NJU-PIN/"
        done
        ;;

    1.1.3) echo "get time resolution for SiC-PIN"
        ./python/add_noise_raser.py output/pin3D/NJU-PIN/_d=10.0_v=-500.0_tmp=300.0_thick=100.0_radius=None 1
        ;;

    1.1.2S) echo "run 3D-SiC batch model with total number, split with step number ..."
        step=10000
		for ((i=0;i<2;i++))
        do
            for ((j=0;j<10;j++))
            do
                ./python/run_batchjob.py pin3D/NJU-PIN \
                "gsignal.py det_name=NJU-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/NJU-PIN/ parameter_alter=True voltage=$[-500-j*20]"
            done
        done
        ;;

	1.1.3S) echo "get time resolution 3D-SiC multi points voltage [-50,-500]"
        ./python/time_scan.py  output/pin3D/NJU-PIN/ scan
		;;

    1.1.4S) echo "get time resolution vs draw voltage"
		./python/time_scan.py  output/pin3D/NJU-PIN/time_resolution_scan.csv draw_voltage 0
		;;

    1.1.1A) echo "Si-PIN basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=HPK-Si-PIN parfile=paras/setting.json"
        ;;

    1.1.2A) echo "batch model with total number, split with step number"
		step=10000
		for ((i=0;i<20;i++))
        do
            ./python/run_batchjob.py pin3D/HPK-Si-PIN \
                "gsignal.py det_name=HPK-Si-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/HPK-Si-PIN/"
        done
        ;;

    1.1.3A) echo "get time resolution for Si-PIN"
        ./python/add_noise_raser.py output/pin3D/HPK-Si-PIN/_d=-1.0_v=200.0_tmp=300.0_thick=50.0_radius=None 1
        ;;

    1.1.1R) echo "ring electrode SiC-PIN basic information for RASER simulation ..."
        raser "./python/gsignal.py det_name=Ring-PIN parfile=paras/setting.json"
        ;;

    1.1.2R) echo "batch model with total number, split with step number"
		step=10000
		for ((i=0;i<20;i++))
        do
            ./python/run_batchjob.py pin3D/Ring-PIN \
                "gsignal.py det_name=Ring-PIN parfile=paras/setting.json scan=True total_e=$step instan=$i output=output/pin3D/Ring-PIN/"
        done
        ;;

    1.1.3R) echo "get time resolution for SiC-PIN"
        ./python/add_noise_raser.py output/pin3D/Ring-PIN/_d=52.0_v=-500.0_tmp=300.0_thick=100.0_radius=None 1
        ;;

    1.1.7) echo "SiC-PIN beam monitor" 
        raser "./python/gsignal.py det_name=NJU-PIN-Beam-monitor parfile=paras/setting.json beammonitor" 
        ;;
        esac
}