from sys import modules
from raser.geometry import R3dDetector
from raser.calcurrent import CalCurrentG4P
from raser.calcurrent import CalCurrentLaser
from raser.elereadout import Amplifier
from raser.setting import Setting
from raser.model import Material
#from raser.source import TCTTracks
#from raser.g4SiITk import SiITk
#from raser.g4simulation import Particles
from raser.devsim import DevsimCal
